### PR TITLE
React-router-dom and ApplicationForm in components dir

### PR DESCRIPTION
**Pull request by Bidon15**

### CODE REVIEW

**Review by Wondertan — COMMENTED** [review]
Pls download `prettier` extension to your editor and apply all suggested styling fixes

**Comment by Bidon15** [comment]
> Pls download `prettier` extension to your editor and apply all suggested styling fixes

Done. Totally forgot this stuff

**Comment by Wondertan** [comment]
Also, install eslint

**Review by Wondertan — APPROVED** [review]

**Comment by Wondertan** [comment]
@Bidon15, checkout recent changes, need to merge that soon

**Pull request merged**
